"""
Django settings for travel project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.template.context_processors import media, static

from config import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_id!=i9jjo%vd3sj_!88byqnv8&ge+%-3u1sk^lgv=(b(u%s51"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'user',
    'home',
    'ksh',
    # 'debug_toolbar',
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'debug_toolbar.middleware.DebugToolbarMiddleware'
    # "home.middleware.PageVisitMiddleware",
]

INTERNAL_IPS=[
    '127.0.0.1',
]
ROOT_URLCONF = "travel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.media",
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "travel.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": Config.DATABASE,
        "USER": Config.USER,
        "PASSWORD": Config.PASSWORD,
        "HOST": Config.HOST,
        "PORT": Config.PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#配置媒体文件
MEDIA_URL = "/media/"
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
#配置静态文件
STATIC_URL = "static/"
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SimpleUI 配置
SIMPLEUI_HOME_PAGE_TITLE = '旅游管理系统'
SIMPLEUI_HOME_ICON = 'fa fa-building'
SIMPLEUI_LOGO = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=travel%20management%20system%20logo%2C%20simple%2C%20modern%2C%20blue%20color%20scheme&image_size=square_hd'
# 自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['后台信息管理', '认证与授权', '旅游信息管理', '用户管理', 'KSH模块'],
    'menus': [
        {
            'name': '后台信息管理',
            'icon': 'fas fa-tachometer-alt',
            'url': '/admin/',
        },
        {
            'name': '认证与授权',
            'icon': 'fas fa-lock',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fas fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '组',
                    'icon': 'fas fa-users',
                    'url': 'auth/group/'
                }
            ]
        },
        {
            'name': '旅游信息管理',
            'icon': 'fas fa-suitcase-rolling',
            'models': [
                {
                    'name': '景点信息',
                    'icon': 'fas fa-map-marker-alt',
                    'url': 'home/travelinfo/'
                },
                {
                    'name': '评论信息',
                    'icon': 'fas fa-comments',
                    'url': 'home/review/'
                },
                {
                    'name': '页面访问',
                    'icon': 'fas fa-eye',
                    'url': 'home/pagevisit/'
                },
{
                    'name': '用户注册数统计',
                    'icon': 'fas fa-eye',
                    'url': 'home/pagevisit/'
                }
            ]
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户信息',
                    'icon': 'fas fa-user-circle',
                    'url': 'user/userinfo/'
                },
                {
                    'name': '用户注册数统计',
                    'icon': 'fas fa-chart-line',
                    'url': 'home/user_stats/'
                }
            ]
        }
    ]
}
