# Generated by Django 5.2.12 on 2026-04-15 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelinfo",
            options={},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(default=0, verbose_name="用户ID")),
                (
                    "username",
                    models.CharField(default="匿名用户", max_length=50, verbose_name="用户名"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1分"), (2, "2分"), (3, "3分"), (4, "4分"), (5, "5分")],
                        verbose_name="评分",
                    ),
                ),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评价时间"),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.travelinfo",
                        verbose_name="景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "景点评价",
                "verbose_name_plural": "景点评价管理",
            },
        ),
        migrations.CreateModel(
            name="TravelRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="目的地")),
                ("season", models.CharField(max_length=20, verbose_name="季节")),
                ("days", models.IntegerField(verbose_name="行程天数")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总预算"
                    ),
                ),
                ("table_content", models.TextField(verbose_name="路线表格内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "旅游路线",
                "verbose_name_plural": "旅游路线管理",
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="景点名称")),
                ("visit_time", models.CharField(max_length=100, verbose_name="游玩时间")),
                ("feature", models.TextField(verbose_name="景色特点")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="预计花费"
                    ),
                ),
                ("order", models.IntegerField(verbose_name="顺序")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.travelroute",
                        verbose_name="旅游路线",
                    ),
                ),
            ],
            options={
                "verbose_name": "路线景点",
                "verbose_name_plural": "路线景点管理",
                "ordering": ["order"],
            },
        ),
    ]
