# Generated by Django 5.2.12 on 2026-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_travelinfo_options_review_travelroute_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=255, verbose_name="页面名称")),
                ("page_url", models.CharField(max_length=500, verbose_name="页面URL")),
                ("visit_count", models.IntegerField(default=0, verbose_name="访问次数")),
                (
                    "first_visit",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次访问时间"),
                ),
                (
                    "last_visit",
                    models.DateTimeField(auto_now=True, verbose_name="最后访问时间"),
                ),
            ],
            options={
                "verbose_name": "页面访问统计",
                "verbose_name_plural": "页面访问统计管理",
                "ordering": ["-visit_count"],
            },
        ),
    ]
