# Generated by Django 5.2.12 on 2026-04-16 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_pagevisit"),
    ]

    operations = []
