# Generated by Django 5.2.12 on 2026-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="spot_name",
            field=models.CharField(default="", max_length=255, verbose_name="景点名称"),
        ),
    ]
