# Generated by Django 5.2.11 on 2026-03-02 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("password", models.CharField(max_length=40, verbose_name="密码")),
                ("uemail", models.CharField(max_length=40, verbose_name="邮箱")),
                (
                    "uaddress",
                    models.CharField(default="", max_length=40, verbose_name="地址"),
                ),
                (
                    "uyoubian",
                    models.CharField(default="", max_length=30, verbose_name="邮箱"),
                ),
                (
                    "uphone",
                    models.CharField(default="", max_length=30, verbose_name="手机号"),
                ),
                (
                    "avatar",
                    models.CharField(default="", max_length=255, verbose_name="头像"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 3, 2, 5, 49, 42, 905914, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
