# Generated by Django 5.2.11 on 2026-03-02 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name_plural": "用户管理"},
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 2, 10, 23, 1, 989167, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
