# Generated by Django 5.2.12 on 2026-04-16 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_userinfo_options_alter_userinfo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=128, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="uyoubian",
            field=models.CharField(default="", max_length=30, verbose_name="邮编"),
        ),
    ]
