# Generated by Django 5.2.12 on 2026-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userinfo_created_at_alter_userinfo_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=20, unique=True, verbose_name="用户名"),
        ),
    ]
