# Generated by Django 5.2.12 on 2026-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_userinfo_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="uemail",
            field=models.CharField(max_length=40, unique=True, verbose_name="邮箱"),
        ),
    ]
